### ISSUE TITLE
Search facility broken on pyvideo.org

### ISSUE THREAD

**Issue by ds33s** [pyvideo/pyvideo#248]
The search facility is no longer working.

For example the following link:
[https://pyvideo.org/search.html?q=celery](https://pyvideo.org/search.html?q=celery)
Used to show all videos related to the 'Celery' library, but now shows no results.

![broken-search](https://user-images.githubusercontent.com/50616783/72736150-16636500-3b95-11ea-8298-da189ad2552c.png)

**Comment by ds33s** [comment]
The issue may be due to the api:

[https://api.pyvideo.org/v1/search?q=celery](https://api.pyvideo.org/v1/search?q=celery)

returning an empty result set:
```json
{
  "status": {
    "total": 1,
    "failed": 0,
    "successful": 1
  },
  "request": {
    "query": {
      "query": "celery"
    },
    "size": 100,
    "from": 0,
    "highlight": null,
    "fields": [
      "title",
      "url",
      "conference",
      "speakers.name",
      "speakers.slug",
      "thumbnail_url",
      "collection_title",
      "collection_url",
      "recorded",
      "recorded_formatted"
    ],
    "facets": {
      "collection": {
        "size": 10,
        "field": "collection_title"
      },
      "speaker": {
        "size": 10,
        "field": "speakers"
      }
    },
    "explain": false,
    "sort": [
      "-_score"
    ],
    "includeLocations": true
  },
  "hits": [],
  "total_hits": 0,
  "max_score": 0,
  "took": 112417,
  "facets": {
    "collection": {
      "field": "collection_title",
      "total": 0,
      "missing": 0,
      "other": 0
    },
    "speaker": {
      "field": "speakers",
      "total": 0,
      "missing": 0,
      "other": 0
    }
  }
}
```

**Comment by zerok** [comment]
Sorry, looks like my server's index got polluted over the holidays. I'll try to find some time tomorrow to fix that. Sorry :(

**Comment by ds33s** [comment]
Thanks for looking into it @zerok - it all seems to be up and running again.

**Comment by zerok** [comment]
I’ve also had to fix a couple of issues in the code itself. With some 
luck, it should run more stable now :)

**Comment by redapple** [comment]
Hi @zerok , I'm getting an HTTP 404 now
e.g. https://api.pyvideo.org/v1/search?q=python
could you have a look?

**Comment by zerok** [comment]
@redapple Hi :) Could it be that that api.pyvideo.org no longer points at my server? It seems to resolve to 45.76.95.160 but should resolve to 46.101.212.176 🙃

**Comment by redapple** [comment]
@zerok , I have absolutely no idea. Probably @logston knows

**Comment by logston** [comment]
Ah, thank you @zerok for pointing that out. I've updated the DNS record. Let's see how it goes. TTL is 10800 so it could take a few hours before we see the change.

**Comment by logston** [comment]
Hmm, looks like the cert is not working in Chrome:
<img width="608" alt="Screen Shot 2020-02-26 at 10 50 17 PM" src="https://user-images.githubusercontent.com/2641765/75410608-7793fc00-58ea-11ea-9740-867be3168994.png">

**Comment by zerok** [comment]
Fixed, sorry about that :)

**Comment by redapple** [comment]
Search is still not working for me.
My firefox console says:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.pyvideo.org/v1/search?q=scrapy. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

**Comment by zerok** [comment]
Now ^_^

**Comment by redapple** [comment]
works for me @zerok ! thank you.
@logston , all good on your end too?

**Comment by logston** [comment]
Looks good! Thanks @zerok and @redapple!
